apiVersion: apps/v1
kind: Deployment
metadata:
  name: pressfaultdetection
  labels:
    app: pressfaultdetection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pressfaultdetection
  template:
    metadata:
      labels:
        app: pressfaultdetection
    spec:
      containers:
        - name: pressfaultdetection
          image: "username/pressfaultdetection:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
