apiVersion: v1
kind: Service
metadata:
  name: pressfaultdetection
  labels:
    app: pressfaultdetection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pressfaultdetection