apiVersion: apps/v1
kind: Deployment
metadata:
  name: paintingprocessmonitoring
  labels:
    app: paintingprocessmonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paintingprocessmonitoring
  template:
    metadata:
      labels:
        app: paintingprocessmonitoring
    spec:
      containers:
        - name: paintingprocessmonitoring
          image: "username/paintingprocessmonitoring:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
