apiVersion: v1
kind: Service
metadata:
  name: paintingprocessmonitoring
  labels:
    app: paintingprocessmonitoring
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: paintingprocessmonitoring