apiVersion: apps/v1
kind: Deployment
metadata:
  name: weldingprocessmonitoring
  labels:
    app: weldingprocessmonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weldingprocessmonitoring
  template:
    metadata:
      labels:
        app: weldingprocessmonitoring
    spec:
      containers:
        - name: weldingprocessmonitoring
          image: "username/weldingprocessmonitoring:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
