apiVersion: v1
kind: Service
metadata:
  name: weldingprocessmonitoring
  labels:
    app: weldingprocessmonitoring
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: weldingprocessmonitoring