apiVersion: apps/v1
kind: Deployment
metadata:
  name: assemblyprocessmonitoring
  labels:
    app: assemblyprocessmonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyprocessmonitoring
  template:
    metadata:
      labels:
        app: assemblyprocessmonitoring
    spec:
      containers:
        - name: assemblyprocessmonitoring
          image: "username/assemblyprocessmonitoring:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
