---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement
  labels:
    app: usermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagement
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      containers:
        - name: usermanagement
          image: username/usermanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  labels:
    app: report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - name: report
          image: username/report:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: approvalmanagement
  labels:
    app: approvalmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approvalmanagement
  template:
    metadata:
      labels:
        app: approvalmanagement
    spec:
      containers:
        - name: approvalmanagement
          image: username/approvalmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pressfaultdetection
  labels:
    app: pressfaultdetection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pressfaultdetection
  template:
    metadata:
      labels:
        app: pressfaultdetection
    spec:
      containers:
        - name: pressfaultdetection
          image: username/pressfaultdetection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  labels:
    app: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: username/chatbot:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paintingprocessmonitoring
  labels:
    app: paintingprocessmonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paintingprocessmonitoring
  template:
    metadata:
      labels:
        app: paintingprocessmonitoring
    spec:
      containers:
        - name: paintingprocessmonitoring
          image: username/paintingprocessmonitoring:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: assemblyprocessmonitoring
  labels:
    app: assemblyprocessmonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyprocessmonitoring
  template:
    metadata:
      labels:
        app: assemblyprocessmonitoring
    spec:
      containers:
        - name: assemblyprocessmonitoring
          image: username/assemblyprocessmonitoring:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weldingprocessmonitoring
  labels:
    app: weldingprocessmonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weldingprocessmonitoring
  template:
    metadata:
      labels:
        app: weldingprocessmonitoring
    spec:
      containers:
        - name: weldingprocessmonitoring
          image: username/weldingprocessmonitoring:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: usermanagement
  labels:
    app: usermanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: usermanagement


---


apiVersion: v1
kind: Service
metadata:
  name: report
  labels:
    app: report
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: report


---


apiVersion: v1
kind: Service
metadata:
  name: approvalmanagement
  labels:
    app: approvalmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: approvalmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: pressfaultdetection
  labels:
    app: pressfaultdetection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pressfaultdetection


---


apiVersion: v1
kind: Service
metadata:
  name: chatbot
  labels:
    app: chatbot
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: chatbot


---


apiVersion: v1
kind: Service
metadata:
  name: paintingprocessmonitoring
  labels:
    app: paintingprocessmonitoring
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: paintingprocessmonitoring


---


apiVersion: v1
kind: Service
metadata:
  name: assemblyprocessmonitoring
  labels:
    app: assemblyprocessmonitoring
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: assemblyprocessmonitoring


---


apiVersion: v1
kind: Service
metadata:
  name: weldingprocessmonitoring
  labels:
    app: weldingprocessmonitoring
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: weldingprocessmonitoring

